site_name: Meine Doku

theme:
  name: material
  language: de
  logo: assets/logo.png
  palette:
    primary: indigo
  features:
    - navigation.expand
    - content.code.copy
    - header.autohide
    - navigation.sections

extra_css:
  - stylesheets/extra_css

nav:
  - Meine Doku: index.md
  - Einrichtung: setup.md
  - Impressum: impressum.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
